### ISSUE TITLE
material::scattering_pdf has return type float but returns a bool

### ISSUE THREAD

**Issue by vilya** [RayTracing/raytracing.github.io#189]
In "Raytracing: The Rest Of Your Life", chapter 6, the code snippet for the `material` class declares the `scattering_pdf` function with a return type of `float` but returns the boolean value `true`. The source code in `material.h` has the same error.

**Comment by hollasch** [comment]
Very strange, I couldn't find an existing issue for this defect.

This has been fixed in the development version of the books, which should be coming out shortly. If you want a sneak peek, check out https://raytracing.github.io/books/RayTracingTheRestOfYourLife.html.

**Comment by vilya** [comment]
Thanks for taking a look! 

I can still see the incorrect code snippet at the link you gave - could it have been the wrong link? It’s the first code snippet in chapter 6. I checked on both the master and the all/changelog branches; I couldn’t see any other branches. 

The error is still there in the source code too, on both branches, at src/TheRestOfYourLife/material.h, lines 58-59.

**Comment by hollasch** [comment]
You're right; thanks for following up. Will fix.

**Comment by hollasch** [comment]
Let me know if I caught everything.
